//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDARENOW_WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assign_Challenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assign_Challenge()
        {
            this.Transactions = new HashSet<Transaction>();
            this.Videos = new HashSet<Videos>();
        }
    
        public int Challenge_ID { get; set; }
        public int Challenge_Type_ID { get; set; }
        public int Challenge_From_ID { get; set; }
        public Nullable<int> Challenge_To_User_ID { get; set; }
        public Nullable<int> Challenge_Approval_Status { get; set; }
        public string Challenge_Description { get; set; }
        public System.DateTime Challenge_Created_Date { get; set; }
        public int Challenge_Duration { get; set; }
        public int Challenge_Status { get; set; }
        public string Challenge_Tittle { get; set; }
        public Nullable<double> Challenge_Amount { get; set; }
        public Nullable<int> Challenge_Winner_ID { get; set; }
    
        public virtual Challenge_Type Challenge_Type { get; set; }
        public virtual User_Accounts User_Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Videos> Videos { get; set; }
    }
}
