//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDARENOW_WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_approve_reject
    {
        public int id { get; set; }
        public int v_id { get; set; }
        public int user_id { get; set; }
        public int status { get; set; }
    
        public virtual Videos Video { get; set; }
    }
}
