//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDARENOW_WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Transaction_ID { get; set; }
        public int Challenge_ID { get; set; }
        public int Credit_User_ID { get; set; }
        public int Debit_User_ID { get; set; }
    
        public virtual Assign_Challenge Assign_Challenge { get; set; }
        public virtual User_Accounts User_Accounts { get; set; }
        public virtual User_Accounts User_Accounts1 { get; set; }
    }
}
