//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDARENOW_WebServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class User_Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Accounts()
        {
            this.Assign_Challenge = new HashSet<Assign_Challenge>();
            this.Transactions = new HashSet<Transaction>();
            this.Transactions1 = new HashSet<Transaction>();
            this.User_Messages = new HashSet<User_Messages>();
        }
    
        public int User_ID { get; set; }
        public string User_FullName { get; set; }
        public string User_Password { get; set; }
        public string User_Gender { get; set; }
        public string User_Email { get; set; }
        public string User_PhoneNumber { get; set; }
        public Nullable<System.DateTime> User_Birthdate { get; set; }
        public Nullable<System.DateTime> User_Registration_Date { get; set; }
        public string User_Profile_Picture { get; set; }
        public int User_Account_Type_ID { get; set; }
        public string User_Facebook_ID { get; set; }
        public Nullable<int> User_Country_ID { get; set; }
        public Nullable<int> User_City_ID { get; set; }
        public string User_Account_Status { get; set; }
        public Nullable<decimal> User_Ratings { get; set; }
        public Nullable<int> User_Challenged_Completed { get; set; }
        public Nullable<int> User_Approval_Rate { get; set; }
        public Nullable<int> User_Total_Earnings { get; set; }
        public double User_Balance_Total_Amount { get; set; }
    
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assign_Challenge> Assign_Challenge { get; set; }
        [JsonIgnore]
        public virtual City City { get; set; }
        [JsonIgnore]
        public virtual Country Country { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions1 { get; set; }
        [JsonIgnore]
        public virtual User_Account_Type User_Account_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Messages> User_Messages { get; set; }
    }
}
