//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDARENOW_WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Messages
    {
        public int Message_ID { get; set; }
        public int User_From_ID { get; set; }
        public int User_To_ID { get; set; }
        public string Message_Timestamp { get; set; }
        public string Message_Description { get; set; }
    
        public virtual User_Accounts User_Accounts { get; set; }
    }
}
