//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDARENOW_WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Account_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Account_Type()
        {
            this.User_Accounts = new HashSet<User_Accounts>();
        }
    
        public int User_Account_Type_ID { get; set; }
        public string User_Account_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Accounts> User_Accounts { get; set; }
    }
}
