//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDARENOW_WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_comments
    {
        public int Comment_ID { get; set; }
        public string Comment_text { get; set; }
        public double Comment_score { get; set; }
        public int Video_ID { get; set; }
        public System.DateTime Comment_Timestamp { get; set; }
        public int User_ID { get; set; }
    
        public virtual Videos Video { get; set; }
    }
}
