//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDARENOW_WebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Videos()
        {
            this.Post_approve_reject = new HashSet<Post_approve_reject>();
            this.Video_comments = new HashSet<Video_comments>();
        }
    
        public int Video_ID { get; set; }
        public string Video_name { get; set; }
        public int Video_Status { get; set; }
        public System.DateTime Video_Upload_Date { get; set; }
        public Nullable<decimal> Video_Score { get; set; }
        public int Challenge_id { get; set; }
        public Nullable<int> Video_isapproved { get; set; }
        public Nullable<int> Video_to_user_id { get; set; }
    
        public virtual Assign_Challenge Assign_Challenge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_approve_reject> Post_approve_reject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_comments> Video_comments { get; set; }
    }
}
